# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-20 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django_hstore.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hstore_data', django_hstore.fields.DictionaryField(editable=False, null=True)),
                ('name', models.CharField(max_length=255, verbose_name=b'What is your name?')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
